language: cpp
sudo: required # need by trusty
dist: trusty   # Ubuntu 14.04 Trusty Tahr

os:
  - linux
  - osx

env:
    - BTYPE="Debug"
    - BTYPE="Release"

matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc

##### 
addons:
  apt:
    packages:
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libassimp-dev
      - libopenscenegraph-dev
      - libgdal-dev
      - doxygen
      - libboost-dev
      - libboost-date-time-dev
      - graphviz

install:
  # FIXME: remove this now hopefully useless environment variable
  - export TRAVIS=YES
  - export WGET="wget --no-check-certificate"
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ] and ["$QT"=="4"]]; then
       # As of december 2016, Homebrew no longer offers qt (qt4): refer to
       #    https://github.com/cartr/homebrew-qt4/issues/5 
       travis_wait 50 brew install cartr/qt4/qt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ] and ["$QT"=="5"]]; then
       # FIXME: following comment seems to be a history glitch...
       # Note: open-scene-graph is not re-installed and hence the native OSG-Qt
       # (that links against Qt4) cannot be used.
       brew install qt5 &&
       brew link qt5 --force; fi
