language: cpp
sudo: required
dist: trusty

os:
  - osx

env:
  - BTYPE="Debug"
  - BTYPE="Release"

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - libboost-date-time-dev
      - libboost-filesystem-dev

install:
  - cmake --version
