language: cpp
sudo: false
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - cmake --version
script: mkdir build && cd build && cmake ../ && make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # to get gcc-4.8
      - george-edison55-precise-backports # to get cmake 3.x
    packages:
      - cmake-data
      - cmake
      - gcc-4.8
      - g++-4.8
install:
  - wget https://github.com/assimp/assimp/archive/v3.2.zip
  - unzip assimp-3.2.zip
  - cd assimp-3.2
  - mkdir build_release
  - cd build_release
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_RULE_MESSAGES=OFF
  - make
  - pwd
  - export ASSIMP_ROOT_DIR=.