language: cpp
sudo: false
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - cmake --version
script: mkdir build && cd build && cmake ../ && make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # to get gcc-4.8
      - george-edison55-precise-backports # to get cmake 3.x
      - dartsim/ppa # to get assimp 3.x
    packages:
      - cmake-data
      - cmake
      - gcc-4.8
      - g++-4.8
      - libassimp-dev
install:
  - pwd