language: cpp

os:
  - linux
  - osx

sudo: required # need by trusty
dist: trusty

compiler:
  - gcc
  - clang

cache: apt # this feature is available only for private repositories

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_CityGMLVisibiliteQtPlugin=ON -DBUILD_CityGMLFloodARQtPlugin=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Release -DBUILD_CityGMLVisibiliteQtPlugin=ON -DBUILD_CityGMLFloodARQtPlugin=ON"

#-------------------------------------------------------------------
# matrix details :
#
#   - 2x gcc    under Linux trusty 14.04 LTS    (debug and release)
#   - 2x clang  under Linux trusty 14.04 LTS    (debug and release)
#
#   - 2x clang  under OS X with Apple LLVM      (debug and release)
#-------------------------------------------------------------------
matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - libqt4-dev
      - libxerces-c-dev
      - libassimp-dev
      - libopenscenegraph-dev
      - libgdal-dev
      - doxygen
      - graphviz

install:
  - export TRAVIS=YES
  - cmake --version
#
# osx :
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt xerces-c assimp doxygen graphviz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install open-scene-graph; fi
  # Fix unstatified dependency of libgdal.1.dylib that looks for
  # libspatialite.5.dylib (version 5) when the libspatialite formula installs
  # libspatialite.7.dylib (version 7). Trick libgdal in getting what it needs:
  # refer to issue #121.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  ln -s /usr/local/lib/libspatialite.dylib /usr/local/lib/libspatialite.5.dylib; fi

script:
  - cd externals/laslib
  - mkdir buildR; cd buildR; cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_RULE_MESSAGES=OFF; make; sudo make install
  - cd .. && cd .. && cd ..
  - mkdir build && cd build && cmake .. $BTYPE
  - make
#  - make test
#
# osx only (add qt5 after qt4 in the same job) :
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink qt; fi # ---> now unlink qt4
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir build_osx_qt5 && cd build_osx_qt5 && cmake .. $BTYPE -DWITH_QT5=YES -DQT5_DIR=/usr/local/opt/qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test; fi
