language: cpp
sudo: required # need by trusty
dist: trusty   # Ubuntu 14.04 Trusty Tahr

cache: apt     # feature available only for private repositories

##### Matrix definition
# For C++ projects, the env, compiler and os (provided as arrays)
# multiply to construct the build matrix. The shallow (refer to 
# excluded configurations) resulting matrix yields 6 jobs:
# - linux:
#   - gcc:   Debug and Release over Qt4 
#   - clang: Debug and Release over Qt4
# - osx:
#   - clang: Debug and Release over Qt4 and Qt5
#     NOTE: under the hood OSX does in fact tow sub-jobs per job,
#           since two Qt versions 4 and 5 are sequentially tested.
# - Win32:  (not dealt with by Travis bu through Appveyor)
#   - VC++: Debug and Release over Qt4 and Qt5

os:
  - linux      # Ubuntu 14.04 Trusty Tahr
  - osx        # Default is OSX 10.9 (2013). Other versions are
               # available, including OSX 10.11 (2015), refer to
               # https://docs.travis-ci.com/user/osx-ci-environment/ 

compiler:
  - gcc
  - clang      # Under OSX the backend is Apple's LLVM

env:
  - BTYPE="-DCMAKE_BUILD_TYPE=Debug -DBUILD_CityGMLVisibiliteQtPlugin=ON -DBUILD_CityGMLFloodARQtPlugin=ON -DBUILD_CityGMLSunlightQtPlugin=ON"
  - BTYPE="-DCMAKE_BUILD_TYPE=Release -DBUILD_CityGMLVisibiliteQtPlugin=ON -DBUILD_CityGMLFloodARQtPlugin=ON -DBUILD_CityGMLSunlightQtPlugin=ON"

matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc

##### 
addons:
  apt:
    packages:
      - libqt4-dev
      - libxerces-c-dev
      - libassimp-dev
      - libopenscenegraph-dev
      - libgdal-dev
      - doxygen
      - graphviz

install:
  - export TRAVIS=YES
  - cmake --version
  # OSX install done through brew:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt xerces-c assimp doxygen graphviz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install open-scene-graph; fi
    # Fix unstatified dependency of libgdal.1.dylib that looks for
    # libspatialite.5.dylib (version 5) when the libspatialite formula installs
    # libspatialite.7.dylib (version 7). Trick libgdal in getting what it needs:
    # refer to issue #121. [osx_image: beta-xcode6.1]
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  ln -s /usr/local/lib/libspatialite.dylib /usr/local/lib/libspatialite.5.dylib; fi

script:
  - cd externals/laslib
  - mkdir buildR; cd buildR; cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_RULE_MESSAGES=OFF; make; sudo make install
  - cd $TRAVIS_BUILD_DIR               # that is our $HOME
  - mkdir build && cd build && cmake .. $BTYPE
  - make
  - ctest
  # OSX only: previous test was against qt4. Try the same but this time
  # against qt5. The following is a perversion of the script target since
  # we start by an internalized sub-install that installs Qt5.
  # Unlinking qt4 suffices to avoid collisions with upcoming install of qt5
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink qt; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd $TRAVIS_BUILD_DIR fi
    # FIXME: make it so the QT5_DIR is not necessary (simplify cmake files)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir build_osx_qt5 && cd build_osx_qt5 && cmake .. $BTYPE -DWITH_QT5=YES -DQT5_DIR=/usr/local/opt/qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ctest; fi
